import tkinter as tk
from tkinter import ttk
from PIL import Image,ImageTk


parent = tk.Tk()
parent.title('Hikvision            DS-9016HFI-ST')
parent .geometry("800x450")
menu = tk.Menu(parent)
live_menu = tk.Menu(menu, tearoff= 'False')
menu.add_cascade(label = 'live view', menu = live_menu)
play_menu = tk.Menu(menu,tearoff = 'False')
menu.add_cascade(label = 'playback', menu = play_menu)
l_menu = tk.Menu(menu,tearoff = 'False')
menu.add_cascade(label = 'log', menu = l_menu)
con_menu = tk.Menu(menu,tearoff = 'False')
menu.add_cascade(label = 'configuration', menu = con_menu)

frame = ttk.Frame(parent, width = 150, height= 380,borderwidth = 2,
                  relief = tk.GROOVE)
frame.pack_propagate(False)
notebook = ttk.Notebook(frame)
tab1 = ttk.Frame(notebook)
label1 = ttk.Label(tab1,text='camera 01')
label1.pack()
label2 = ttk.Label(tab1,text='camera 02')
label2.pack()
label3 = ttk.Label(tab1,text='camera 3')
label3.pack()
label4 = ttk.Label(tab1,text='camera 04')
label4.pack()
label5 = ttk.Label(tab1,text='camera 05')
label5.pack()
label6 = ttk.Label(tab1,text='camera 06')
label6.pack()
label7 = ttk.Label(tab1,text='camera 07')
label7.pack()
label8 = ttk.Label(tab1,text='camera 08')
label8.pack()
label9 = ttk.Label(tab1,text='camera 09')
label9.pack()
label10 = ttk.Label(tab1,text='camera 10')
label10.pack()
label11 = ttk.Label(tab1,text='camera 11')
label11.pack()
label12 = ttk.Label(tab1,text='camera 12')
label12.pack()
label13 = ttk.Label(tab1,text='camera 13')
label13.pack()
label14 = ttk.Label(tab1,text='camera 14')
label14.pack()
label15 = ttk.Label(tab1,text='camera 15')
label15.pack()
label16 = ttk.Label(tab1,text='camera 16')
label16.pack()



notebook.add(tab1, text='Embedded net DVR')
notebook.pack()

frame.place(x=5, y=10)
frame1 = ttk.Frame(parent, width=600, height=500,borderwidth = 5,relief = 'ridge')
frame1.pack_propagate(False)

arr_image = Image.open('sink.png').resize((50,10))
arrow21_image_tk = ImageTk.PhotoImage(arr_image)
label1 = ttk.Label(frame1,text = 'hikvision',background = 'black')
label2 = ttk.Label(frame1,text = 'hikvision',background = 'black')
label3 = ttk.Label(frame1,text = 'label3',background = 'black')
label4 = ttk.Label(frame1,text = 'label4',background = 'black')
label5 = ttk.Label(frame1,text = 'label5',background = 'black')
label6 = ttk.Label(frame1,text = 'label6',background = 'black')
label7 = ttk.Label(frame1,text = 'label7',background = 'black')
label8 = ttk.Label(frame1,text = 'label8',background = 'black')
label9 = ttk.Label(frame1,text = 'hikvision',background = 'black')
label10 = ttk.Label(frame1,text = 'hikvision',background = 'black')
label11 = ttk.Label(frame1,text = 'label3',background = 'black')
label12= ttk.Label(frame1,text = 'label4',background = 'black')
label13= ttk.Label(frame1,text = 'label5',background = 'black')
label14= ttk.Label(frame1,text = 'label6',background = 'black')
label15= ttk.Label(frame1,text = 'label7',background = 'black')
label16= ttk.Label(frame1,text = 'label8',background = 'black')
parent.columnconfigure((0,1,2,3), weight= 20)
# parent.columnconfigure(1, weight= 20)
# parent.columnconfigure(2, weight= 20)
# parent.columnconfigure(3, weight= 20)
parent.rowconfigure((0,1,2,3),weight=120)
# frame.rowconfigure(1,weight=20)
# parent.rowconfigure(2,weight=120)
# parent.rowconfigure(3,weight=120)
label1.grid(row=0,column= 0,padx = 2,pady=2,ipadx=30,ipady=30)
label2.grid(row = 0,column=1,padx = 2,pady=2,ipadx=30,ipady=30)
label3.grid(row = 0,column=2,padx = 2,pady=2,ipadx=30,ipady=30)
label4.grid(row = 0,column=3,padx = 2,pady=2,ipadx=30,ipady=30)
label5.grid(row = 1,column=0,padx = 1,pady=1,ipadx=38,ipady=30)
label6.grid(row = 1,column=1,padx = 1,pady=1,ipadx=38,ipady=30)
label7.grid(row = 1,column=2,padx = 1,pady=1,ipadx=30,ipady=30)
label8.grid(row = 1,column=3,padx = 1,pady=1,ipadx=30,ipady=30)
label9.grid(row = 2,column=0,padx = 3,pady=3,ipadx=30,ipady=30)
label10.grid(row = 2,column=1,padx = 3,pady=3,ipadx=30,ipady=30)
label11.grid(row = 2,column=2,padx = 3,pady=3,ipadx=30,ipady=30)
label12.grid(row = 2,column=3,padx = 3,pady=3,ipadx=30,ipady=30)
label13.grid(row = 3,column=0,padx = 3,pady=3,ipadx=38,ipady=30)
label14.grid(row = 3,column=1,padx = 3,pady=3,ipadx=38,ipady=30)
label15.grid(row = 3,column=2,padx = 3,pady=3,ipadx=31,ipady=30)
label16.grid(row = 3,column=3,padx = 3,pady=3,ipadx=31,ipady=30)
frame1.place(x=160, y=10)

frame2 = ttk.Frame(parent, width = 455,height=50,
                   borderwidth= 2,relief = tk.GROOVE)

image_original = Image.open('cam.ico').resize((20,20))
image_tk = ImageTk.PhotoImage(image_original)

fil_image = Image.open('rac2.ico').resize((20,20))
file_image_tk = ImageTk.PhotoImage(fil_image)

mov_image = Image.open('vcam.ico').resize((20,20))
movie_image_tk = ImageTk.PhotoImage(mov_image)

zoo_image = Image.open('zom.ico').resize((20,20))
zoom_image_tk = ImageTk.PhotoImage(zoo_image)

zoo_image = Image.open('zom.ico').resize((20,20))
zoom_image_tk = ImageTk.PhotoImage(zoo_image)

arr_image = Image.open('larr.ico').resize((20,20))
arrow_image_tk = ImageTk.PhotoImage(arr_image)

arro_image = Image.open('narr.ico').resize((20,20))
next_image_tk = ImageTk.PhotoImage(arro_image)

mic_image = Image.open('mic.ico').resize((20,20))
Mice_image_tk = ImageTk.PhotoImage(mic_image)

mut_image = Image.open('mute.ico').resize((20,20))
mute_image_tk = ImageTk.PhotoImage(mut_image)
resiz_image = Image.open('resize.ico').resize((20,20))
resize_image_tk = ImageTk.PhotoImage(resiz_image)


button = ttk.Button(frame2,image = image_tk)
button.place(x=200,y=0)
button1 = ttk.Button(frame2,image = file_image_tk)
button1.place(x=170,y=0)
button2 = ttk.Button(frame2,image = movie_image_tk)
button2.place(x=230,y=0)
button3 = ttk.Button(frame2,image = zoom_image_tk)
button3.place(x=260,y=0)
button4 = ttk.Button(frame2,image = arrow_image_tk)
button4.place(x=290,y=0)
button5 = ttk.Button(frame2,image = next_image_tk)
button5.place(x=320,y=0)
button6 = ttk.Button(frame2,image = Mice_image_tk)
button6.place(x=350,y=0)
button7 = ttk.Button(frame2,image = mute_image_tk)
button7.place(x=380,y=0)
button8 = ttk.Button(frame2,image = resize_image_tk)
button8.place(x=410,y=0)
frame2.pack_propagate(False)

frame2.place(x= 160,y=360)

frame3 = ttk.Frame(parent, width = 200,height=350,borderwidth= 2,relief = tk.GROOVE)
frame3.pack_propagate(False)
label9 =ttk.Label(frame3,text='PTZ                                    ',background='white')
label9.place(x=0,y=0)

arr_image = Image.open('lefcorn.png').resize((10,10))
arrow1_image_tk = ImageTk.PhotoImage(arr_image)
arr_image = Image.open('arrup.png').resize((10,10))
arrow2_image_tk = ImageTk.PhotoImage(arr_image)
arr_image = Image.open('arrrigh.png').resize((10,10))
arrow3_image_tk = ImageTk.PhotoImage(arr_image)
arr_image = Image.open('leftarrow.png').resize((10,10))
arrow4_image_tk = ImageTk.PhotoImage(arr_image)
arr_image = Image.open('circleup.png').resize((10,10))
arrow5_image_tk = ImageTk.PhotoImage(arr_image)
arr_image = Image.open('arrowright.png').resize((10,10))
arrow6_image_tk = ImageTk.PhotoImage(arr_image)
arr_image = Image.open('leftcorner.png').resize((10,10))
arrow7_image_tk = ImageTk.PhotoImage(arr_image)
arr_image = Image.open('downarrow.png').resize((10,10))
arrow8_image_tk = ImageTk.PhotoImage(arr_image)
arr_image = Image.open('rightcorner.png').resize((10,10))
arrow9_image_tk = ImageTk.PhotoImage(arr_image)
arr_image = Image.open('plus.png').resize((10,10))
arrow10_image_tk = ImageTk.PhotoImage(arr_image)
arr_image = Image.open('plus.png').resize((10,10))
arrow11_image_tk = ImageTk.PhotoImage(arr_image)
arr_image = Image.open('plus.png').resize((10,10))
arrow12_image_tk = ImageTk.PhotoImage(arr_image)
arr_image = Image.open('search.png').resize((10,10))
arrow13_image_tk = ImageTk.PhotoImage(arr_image)
arr_image = Image.open('music.png').resize((10,10))
arrow14_image_tk = ImageTk.PhotoImage(arr_image)
arr_image = Image.open('star.png').resize((10,10))
arrow15_image_tk = ImageTk.PhotoImage(arr_image)
arr_image = Image.open('minus.png').resize((10,10))
arrow16_image_tk = ImageTk.PhotoImage(arr_image)
arr_image = Image.open('minus.png').resize((10,10))
arrow17_image_tk = ImageTk.PhotoImage(arr_image)
arr_image = Image.open('minus.png').resize((10,10))
arrow18_image_tk = ImageTk.PhotoImage(arr_image)
arr_image = Image.open('flag.png').resize((40,10))
arrow19_image_tk = ImageTk.PhotoImage(arr_image)
arr_image = Image.open('bulb1.ico').resize((50,10))
arrow20_image_tk = ImageTk.PhotoImage(arr_image)
arr_image = Image.open('sink.png').resize((50,10))
arrow21_image_tk = ImageTk.PhotoImage(arr_image)



button1 = ttk.Button(frame3,image = arrow1_image_tk)
button1.place(x=0,y=20)
button2 = ttk.Button(frame3,image = arrow2_image_tk)
button2.place(x=20,y=20)
button3 = ttk.Button(frame3,image = arrow3_image_tk)
button3.place(x=40,y=20)
button4 = ttk.Button(frame3,image = arrow4_image_tk)
button4.place(x=0,y=40)
button5 = ttk.Button(frame3,image = arrow5_image_tk)
button5.place(x=20,y=40)
button6 = ttk.Button(frame3,image = arrow6_image_tk)
button6.place(x=40,y=40)
button7 = ttk.Button(frame3,image = arrow7_image_tk)
button7.place(x=0,y=60)
button8 = ttk.Button(frame3,image = arrow8_image_tk)
button8.place(x=20,y=60)
button9 = ttk.Button(frame3,image = arrow9_image_tk)
button9.place(x=40,y=60)
button10 = ttk.Button(frame3,image = arrow10_image_tk)
button10.place(x=60,y=20)
button11 = ttk.Button(frame3,image = arrow11_image_tk)
button11.place(x=60,y=40)
button12 = ttk.Button(frame3,image = arrow12_image_tk)
button12.place(x=60,y=60)
button13 = ttk.Button(frame3,image = arrow13_image_tk)
button13.place(x=80,y=20)
button14 = ttk.Button(frame3,image = arrow14_image_tk)
button14.place(x=80,y=40)
button15 = ttk.Button(frame3,image = arrow15_image_tk)
button15.place(x=80,y=60)
button16 = ttk.Button(frame3,image = arrow16_image_tk)
button16.place(x=100,y=20)
button17 = ttk.Button(frame3,image = arrow17_image_tk)
button17.place(x=100,y=40)
button18 = ttk.Button(frame3,image = arrow18_image_tk)
button18.place(x=100,y=60)
button20 = ttk.Button(frame3,image = arrow20_image_tk)
button20.place(x=0,y=80)
button21 = ttk.Button(frame3,image = arrow21_image_tk)
button21.place(x=60,y=80)

sb = ttk.Scrollbar(frame3)
sb.pack(side='right', fill='y',ipadx=15)

mylist = tk.Listbox(frame3, yscrollcommand=sb.set)

for i in range(16):
    mylist.insert('end',  f"preset {i}")
button19 = ttk.Button(frame3,image = arrow19_image_tk)
button19.place(x=0,y=250)
mylist.pack(side='left',pady=100,fill='both',ipadx=20)
sb.config(command=mylist.yview)



frame3.place(x= 620,y=10)

frame4 = ttk.Frame(parent, width = 150,height=40,borderwidth= 10,relief = tk.GROOVE)
frame4.pack_propagate(False)
items = ('HD','Mp4')
video_string = tk.StringVar(value = 'Video parameters')
combo = ttk.Combobox(frame4,  textvariable=video_string)
combo['value'] = items
combo.pack()
frame4.place(x= 620,y=365)


parent.configure(menu = menu)
parent.mainloop()